version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=alex
      - MONGO_PASSWORD=parola
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alex
      - MONGO_INITDB_ROOT_PASSWORD=parola
  